apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-example-USER
  namespace: kcm-system
spec:
  template: aws-standalone-cp-0-2-0
  credential: aws-credential
  config:
    clusterLabels:
      type: aws
      group: demo
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: false
    region: eu-central-1
    worker:
      instanceType: t3.medium
      rootVolumeSize: 16
    workersNumber: 1
