apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: hpe-csi-driver-2-5-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: hpe-csi-driver
      version: 2.5.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
