apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: kserve-crd-v0-15-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: kserve-crd
      version: v0.15.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
